### PR TITLE
[Site] Updated home page logo

### LINKED ISSUE #138: Update the Logo on Home page.
**Current State of the GetNighthawk.dev site**

The current logo on the Getnighthawk home page is the same as the navbar logo.

Screenshot 2021-06-15 at 21 19 19

**Desired State of the GetNighthawk.dev site**

the logo on the Getnigthawk home page should be updated to look like this.

Screenshot 2021-06-15 at 21 22 19

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

This PR fixes #138 

**Description**
The current logo on the Getnighthawk home page is the same as the navbar logo. 

- Updated Home logo for desktop
- Updated Styles for smaller devices

## After Changes
Screenshot from 2021-06-18 14-04-34

Screenshot from 2021-06-18 14-04-46

**Notes for Reviewers**
Let me know if there are any other changes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@Jashpatel1 @Anita-ihuman Need little help here. Thank you

Error at Mixed content

Screenshot from 2021-06-18 15-09-35

**Comment by Jashpatel1** [comment]
> @Jashpatel1 @Anita-ihuman Need little help here. Thank you
> 
> Error at Mixed content
> 
> Screenshot from 2021-06-18 15-09-35

Can you update the link in about.html to `https://` instead of `http://` . The issue came from somewhere else but you can fix it.

**Comment by NikhilSharma03** [comment]
It's Fixed 😊 Thank you @Jashpatel1.

**Review by Jashpatel1 — APPROVED** [review]
That was quick. Thanks @NikhilSharma03

**Pull request merged**
