### PR TITLE
Added Open Graph tags for better sharing previews

### LINKED ISSUE #235: [Site] : Set the Open Graph image for the nighthawk site
**Current State of the GetNighthawk.dev site**

The nighthawk project doesn't have required OG (Opengraps) tags 

image

**Desired State of the GetNighthawk.dev site**

Add required og: tags for the image so that it has a preview image while sharing links associated with it on any social network or app that utilizes rich previews!!

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

Check out [this](https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/#what-is-open-graph) article if you are not familiar with OpenGraph tags

### PR DESCRIPTION
**Pull request by sidd-oo**
Signed-off-by: sidd-oo <sahoosiddharth3@gmail.com>

**Description**
Added Open Graph Tags for better sharing preview on social media for the nighthawk site.

This PR fixes #235 

**Notes for Reviewers**
[New Image](https://github.com/layer5io/getnighthawk/pull/236#issuecomment-1054313498) shared by Lee is added for right alignment and better share preview on social media.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhijay007** [comment]
@sidd-oo I think you used the wrong image, use the image that is provided by @lee in one of the last comments of this [PR](https://github.com/layer5io/getnighthawk/pull/236)

**Comment by sidd-oo** [comment]
> @sidd-oo I think you used the wrong image, use the image that is provided by @lee in one of the last comments of this [PR](https://github.com/layer5io/getnighthawk/pull/236)

No, I used the right image @Abhijay007. But turns out to be the image provided by Lee is not getting aligned properly inside the OpenGraph sharing previews. So I tried to change the dimensions which were recommended(1200 x 630) and it get aligned properly for LinkedIn, discord but not for Twitter.

Do share any workaround you have in your mind to make it work for Twitter ? @Abhijay007

**Comment by sidd-oo** [comment]
@Abhijay007  You can check the previews from this [link](https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-257--getnighthawk.netlify.app%2F/). 
image

P.S - For LinkedIn actually it is working properly but in this above link, it is showing some false results.

**Comment by Abhijay007** [comment]
> @Abhijay007 You can check the previews from this [link](https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-257--getnighthawk.netlify.app%2F/). image
> 
> P.S - For LinkedIn actually it is working properly but in this above link, it is showing some false results.

check for Facebook here : https://developers.facebook.com/tools/debug/
and for Twitter here : https://cards-dev.twitter.com/validator

**Comment by leecalcote** [comment]
It seems that we just can't win or at least not 100% 😅

**Comment by leecalcote** [comment]
The version of the logo to be used as the one that has the word Nighthawk in it.

**Comment by Abhijay007** [comment]
> The version of the logo to be used as the one that has the word Nighthawk in it.

[This](https://github.com/layer5io/getnighthawk/pull/236#issuecomment-1054313498) one

**Comment by Abhijay007** [comment]
> > The version of the logo to be used as the one that has the word Nighthawk in it.
> 
> [This](https://github.com/layer5io/getnighthawk/pull/236#issuecomment-1054313498) one

But I think @sidd-oo used the same, don't know why it not giving desired results 😅

**Review by alphaX86 — APPROVED** [review]
I'm able to see the image with the title "Nighthawk". So LGTM?

**Comment by alphaX86** [comment]
@warunicorn19 comments?? 👀

**Pull request merged**
