### PR TITLE
Added responsive heading and paragraph

### LINKED ISSUE #168: [Site] Mobile responsiveness for Home page
**Current State of the GetNighthawk.dev site**
chrome_Ww5xyovfub

**Desired State of the GetNighthawk.dev site**
chrome_1cgVpCqofN

The text needs to be center-aligned for both the sections

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Added responsive heading and paragraph in the Index page so that when user view in the mobile view heading and paragraph automatically changes to center align

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

**Description**

This PR fixes #168 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@AnshumanDhiman good work here, but just a small nitpick, the ratio of the font size of the header compared to the text looks a little weird in mobile view.

Screenshot_20210820-100702

Could you please reduce the size of the header, only for mobile view. I think that'll look better

**Comment by AnshumanDhiman** [comment]
> @AnshumanDhiman good work here, but just a small nitpick, the ratio of the font size of the header compared to the text looks a little weird in mobile view.
> 
> Screenshot_20210820-100702
> 
> Could you please reduce the size of the header, only for mobile view. I think that'll look better

Ok @warunicorn19 I will update this for mobile view

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Screenshot 2021-08-23 at 4 49 58 PM
 
Seems like you missed one😅, could you please do same to this header too.

**Comment by AnshumanDhiman** [comment]
@warunicorn19 I changed the heading. What I saw is that there are many bugs like this when switching to the mobile view so I think we should make an issue I will be working on this...

**Review by warunicorn19 — APPROVED** [review]
@AnshumanDhiman Yes, I see the same. Could you create an issue for it? For now this PR looks good.

**Review by vinayaksh42 — APPROVED** [review]
Great work @AnshumanDhiman, also it would be nice to open up a new issue for mobile view related issues

**Pull request merged**
