### PR TITLE
Fixed Footer Alignment

### LINKED ISSUE #42: [Site] Footer improvements
**Current Behavior**

Currently, the footer lacks alignment and proper placement of contents

**Desired Behavior**

Screenshot from Figma:
chrome_ydzZIE5D4n

---
**Resources**

**Alternatives / Additional Context**

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #42 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

Screenshot_2021-02-14 GetNighthawk
Screen Shot 2021-02-14 at 01 22 12

### CODE REVIEW

**Comment by leecalcote** [comment]
Good, good.

**Comment by vinayaksh42** [comment]
Chrome (windows):
n2KsDN04qo
There is a second vertical scroll bar coming up, can you kindly check that.

**Comment by vinayaksh42** [comment]
Try adding 
```css
overflow: hidden;
```
to the body of the container of the footer.

**Review by vinayaksh42 — CHANGES_REQUESTED** [review]
Add 
```css
overflow: hidden;
```
to the container of the footer or the entire HTML body for fixing the additional vertical scroll bar.

**Review by vinayaksh42 — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Thank you, @chinmaym07 @vinayaksh42

**Pull request merged**
