### PR TITLE
Issue-254 (Chore): Fixed Sidebar in mobile view

### LINKED ISSUE #254: [Docs] Sidebar in mobile view
**Current State of the GetNighthawk.dev site**
The button to open the sidebar on [Nighthawk Docs ](https://getnighthawk.dev/docs) is placed such that it covers the content on the page and its purpose isn't very clear.
<table>
<td>
Screenshot 2022-02-22 at 2 39 46 PM
</td>
<td>
Screenshot 2022-02-22 at 2 40 26 PM
</td>
</table>

**Desired State of the GetNighthawk.dev site**
Preferably, move the button to the top-left corner. Could be converted into a semi-circle to show only a part of the button appearing from the edge.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Fixed Sidebar in mobile view, made it rectangle and placed it to the edge 

This PR fixes #254 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhijay007** [comment]
PS : sorry for the late PR 😅

**Comment by sidd-oo** [comment]
Looks good to me! 
Keep up the good work @Abhijay007

**Review by YashKamboj — CHANGES_REQUESTED** [review]
@Abhijay007  It would be great if you move the button to the right when the menu is expanded. Some shadow would look really nice. the button is cut off from below??
Screenshot (5)

**Comment by Abhijay007** [comment]
> @Abhijay007 It would be great if you move the button to the right when the menu is expanded. Some shadow would look really nice. the button is cut off from below?? Screenshot (5)

Ya I will move it to the right on expansion and the button is not getting cut ,it is due to preview link 😅

**Comment by debo19** [comment]
@Abhijay007 any update on this? Can we discuss this on the call tomorrow?

**Comment by Abhijay007** [comment]
> @Abhijay007 any update on this? Can we discuss this on the call tomorrow?

@debo19 I am getting some errors while running the nighthawk project locally and to resolve that I need to switch my installed ruby version, I will update you on this :)

**Review by YashKamboj — APPROVED** [review]
LGTM!!!

**Pull request merged**
