### PR TITLE
Link fix for buttons!

### LINKED ISSUE #81: [Site] Link fix for all the Buttons
**Current State of the GetNighthawk.dev site**
A few buttons are not linked to any link

**Desired State of the GetNighthawk.dev site**
Requires linking of all the buttons to proper links
 - Join Us - https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#
 - Need link for Ask Us button
 - Need link for Learn More button

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by soham4abc**
**Description**

This PR fixes #81

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by soham4abc** [comment]
If any change of links required pls request a change with the respective link change! Happy to help.

**Comment by vinayaksh42** [comment]
> If any change of links required pls request a change with the respective link change! Happy to help.

[Get started] Instead of redirecting them to that google docs, It would be great if you could redirect them to the docs section within the website.
[Join us] use the slack invitation link http://slack.layer5.io/ (the same as on https://layer5.io/community)

Also, make the anchor tag open the link in a new tab in case the link leads to some outside source.

**Comment by soham4abc** [comment]
> > If any change of links required pls request a change with the respective link change! Happy to help.
> 
> [Get started] Instead of redirecting them to that google docs, It would be great if you could redirect them to the docs section within the website.
> [Join us] use the slack invitation link http://slack.layer5.io/ (the same as on https://layer5.io/community)
> 
> Also, make the anchor tag open the link in a new tab in case the link leads to some outside source.

All changes done as per request, Please do review!!

**Review by vinayaksh42 — APPROVED** [review]
Great work @soham4abc

**Comment by leecalcote** [comment]
😎

**Pull request merged**
