### PR TITLE
 updated revised logo

### LINKED ISSUE #95: [Site] Project logo revision
**Current State of the GetNighthawk.dev site**
The GetNighthawk logo has been revised. The logo on the site needs updated.

**Desired State of the GetNighthawk.dev site**
New logo is here - https://layer5.io/brand/getnighthawk-brand-kit.zip

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
The GetNighthawk logo was updated to the revised logo
This PR fixes #95 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by cekbote — APPROVED** [review]
LGTM

**Review by cekbote — COMMENTED** [review]
I guess it would be better to have a different name (without the space), probably getnighthawk-logo-new.svg (just for consistency in the naming conventions)

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
I agree with @cekbote , please rename the file to `getnighthawk-logo.svg` (no `new` word required) and also always avoid spacing in filename.
And, please do REPLACE the `PNG` version of the image as well.

**Comment by Anita-ihuman** [comment]
Thank you @Nikhil-Ladha  and @cekbote for pointing that out.

**Comment by Nikhil-Ladha** [comment]
@Anita-ihuman, please add/replace the PNG images as well.

**Comment by Anita-ihuman** [comment]
> @Anita-ihuman, please add/replace the PNG images as well.

I am a bit confused sorry, Which PNG images am I to replace?

**Comment by Nikhil-Ladha** [comment]
> > @Anita-ihuman, please add/replace the PNG images as well.
> 
> I am a bit confused sorry, Which PNG images am I to replace?

The ones that you are deleting. Replace that with the new ones.

**Comment by vinayaksh42** [comment]
> > @Anita-ihuman, please add/replace the PNG images as well.
> 
> I am a bit confused sorry, Which PNG images am I to replace?

This one docs/assets/images/logos/getnighthawk-logo.png and docs/assets/images/logos/getnighthawk.png

**Comment by Anita-ihuman** [comment]
That is, the Logo with Icon and name? because I have already added the icon in PNG

**Comment by Nikhil-Ladha** [comment]
> That is, the Logo with Icon and name? because I have already added the icon in PNG

In this PR you are removing 2 `.png` files, right?
Now, those 2 `.png` files need to replaced by the new `.png` logos. You can find the updated logos in the community drive.

**Comment by Nikhil-Ladha** [comment]
So so sorry, now I see the area of confusion. Github should properly list which files are added and which are being deleted in the PR.
I see you are already replacing 2 of the logos in the PR.
Just one thing you can add in this PR is, images with name and name it something like `getnighthawk-log-with-name.png` and `getnighthawk-log-with-name.svg`.

I am really sorry for the mess up I have done earlier.

**Comment by Nikhil-Ladha** [comment]
nit: log-> logo
I am doing disasters today. Pardon me 😅

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you for sticking around @Anita-ihuman 🙂

**Pull request merged**
