### PR TITLE
add float navigation to docs

### LINKED ISSUE #88: [Site] Multiple burger menu in Mobile view for Docs Page
**Current State of the GetNighthawk.dev site**
Currently, there are 2 burger menus when we switch to the mobile view on the Docs page.

**Desired State of the GetNighthawk.dev site**
As discussed in the March 29th 2021 website meeting: Addition of a floating menu for the Docs section. In a similar way as it is on https://reactjs.org/docs/getting-started.html Any other suitable way of doing this can also be approached.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Sunnyio**
Signed-off-by: Sunny Kumar <sunny514173@gmail.com>

**Description**
Changed navigation on the documentation page.
This PR fixes #88

**Notes for Reviewers**
Added a floating navigation button for smaller screens.
Changed the styles of navigation on docs.
Added the responsive design to adaptive load controller slides.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@Sunnyio This is looking good. But one thing, the button in the right bottom impersonate to be `Back To Button` so instead, we can either put the button at 

- Top Left without float position 
- Bottom Left with float postioning

oie_6g7oFNu3nhMY (1)

**Comment by Sunnyio** [comment]
> @Sunnyio This is looking good. But one thing, the button in the right bottom impersonate to be `Back To Top` so instead, we can either put the button at
> 
> * Top Left without float position ( the button facing right)
> * Bottom Left with float positioning ( the button facing right)
> * and the effect comes from left to right
> 
> oie_6g7oFNu3nhMY (1)

I have shifted the float menu button to the bottom left however I could not implement any transition effect.

**Review by NikhilSharma03 — APPROVED** [review]
LGTM :+1:. Thanks.

**Comment by leecalcote** [comment]
Thank you for reviewing this @NikhilSharma03

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
