### PR TITLE
updated year

### LINKED ISSUE #260: update the year in the footer section
#### Current Behavior

The year in the footer section need to change and automate it so we do not have to change manually

#### Screenshots/Logs

Screenshot from 2022-04-10 21-59-40

#### Environment

- **Host OS:** Linux 

---

#### Contributor Resources

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
  - 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Axit Patel <patelakshit2025@gmail.com>

This PR fixes #260 

**Notes for Reviewers**
I have automate the year in the footer section

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
Hi @asubedy, @leecalcote please do have a look

**Review by Abhijay007 — APPROVED** [review]
LGTM 👍

**Comment by Akshit42-hue** [comment]
Thanks for the review @Abhijay007 👍

**Review by asubedy — APPROVED** [review]
LGTM 🚀

**Comment by warunicorn19** [comment]
LGTM, Thank you @Akshit42-hue

**Pull request merged**
