### PR TITLE
changed broken link

### LINKED ISSUE #156: [Site] Dead link - Docs/Section1/overview
**Current State of the GetNighthawk.dev site**
request release timings broken link on Docs/Section1/overview
(https://github.com/layer5io/getnighthawk/blob/master/docs/collections/_docs/really-using-getnighthawk.md)

**Desired State of the GetNighthawk.dev site**
Remove the broken link (anchor tag)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

**Description**
Removed the broken link at docs/section1/overview

This PR fixes #156

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vinayaksh42** [comment]
@AnshumanDhiman Nice first Contribution!
Changes Look good to me

**Comment by warunicorn19** [comment]
@vinayaksh42 could you please tell me what is changed in cache/Jekyll file?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 could you please tell me what is changed in cache/Jekyll file? Can't seem to recall seeing that change before 🤔

by looking at the file https://github.com/layer5io/getnighthawk/blob/master/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910, I think it's related to jekyll setting.
It isn't effecting the website but we can remove it.

**Comment by leecalcote** [comment]
I love seeing a PR from @AnshumanDhiman. 🥳

**Comment by AnshumanDhiman** [comment]
> I love seeing a PR from @AnshumanDhiman. 🥳

Thank you @leecalcote

**Pull request merged**
