### PR TITLE
update the footer to bring down copyright text

### PR DESCRIPTION
**Pull request by Grumpyyash**
Signed-off-by: Yash Vardhan <yashvardhan513@gmail.com>

Updated the footer to bring down the copyright text and align them as discussed.

footer

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Much improved.

**Review by leecalcote — APPROVED** [review]

**Comment by vinayaksh42** [comment]
Looks better now, nice work @Grumpyyash

**Comment by Grumpyyash** [comment]
Should we merge these changes?

**Comment by Grumpyyash** [comment]
This PR also resolves #77

**Comment by Grumpyyash** [comment]
@leecalcote I have done the necessary changes into it, please have a look

**Comment by leecalcote** [comment]
Good stuff. 😀

**Pull request merged**
