### PR TITLE
[Site] Updated Footer ul style --signoff

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
- Updated footer ul style

## Current Site

Screenshot from 2021-06-12 18-38-56

## After Changes

Screenshot from 2021-06-13 18-58-50

**Notes for Reviewers**
Let me know if there are any other changes we can make. Thank you.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @NikhilSharma03. We're talking about you on today's Websites call. 🙂

**Comment by NikhilSharma03** [comment]
@leecalcote Sorry. Actually, I did not know about the weekly meeting. Now that I've put it on my calendar, I'll definitely be in the meeting starting next Monday.🚀
As I was mentioned in the meeting, if there is any task needed to do, Let me know I would love to contribute.😊  
Thank you.

**Review by Jashpatel1 — COMMENTED** [review]
Looks great. Can you also increase the size of those links and icons in the footer?

**Comment by NikhilSharma03** [comment]
@Jashpatel1 Yeah sure.

**Comment by Jashpatel1** [comment]
> @Jashpatel1 Yeah sure.
> 
> ## After Updates
> Screenshot from 2021-06-15 16-23-06

Looks good. But, I meant to increase them for desktop view. Could you please make the required changes?

**Comment by NikhilSharma03** [comment]
@Jashpatel1 Yeah sure.

**Comment by NikhilSharma03** [comment]
## After Changes

Screenshot from 2021-06-16 21-36-47

@Jashpatel1 Can you please review. Thank you.

**Comment by Jashpatel1** [comment]
> ## After Changes
> Screenshot from 2021-06-16 21-36-47
> 
> @Jashpatel1 Can you please review. Thank you.

Can you try increasing a bit more?

**Comment by Jashpatel1** [comment]
> > > ## After Changes
> > > @Jashpatel1 Can you please review. Thank you.
> > 
> > 
> > Can you try increasing a bit more?
> 
> Yeah Sure. Links only? or social icons also. coz I think social icons are of correct sizes. Let me know. Thank you.

Links only.

**Comment by NikhilSharma03** [comment]
@Jashpatel1 Can you please review?
- Updated font size to 1rem. Now it's okay or we can still make changes.

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Great work here @NikhilSharma03

**Pull request merged**
