### PR TITLE
[Refix] Label Commenter Workflow

### PR DESCRIPTION
**Pull request by amino19**
Signed-off-by: amino19 <anshumaankrprasad76@gmail.com>

**Description**
CI Workflow for `Label Commenter` is failing, refixed indentation.

This PR fixes #180 #181 

**Notes for Reviewers**
@navendu-pottekkat & @warunicorn19: Sorry for the inconvenience caused, this pull request will fix it!

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — COMMENTED** [review]
No problem @amino19 , thanks for the fix.🙏

**Review by warunicorn19 — APPROVED** [review]

**Comment by amino19** [comment]
@warunicorn19: I really concern about workflows propagation, I'm here, till that does not work properly.
Pl feel free to ping me here or on slack! : )

**Comment by warunicorn19** [comment]
@amino19 that's great to hear, thank you, but I think workflow is still not working could you please take a look

**Comment by amino19** [comment]
> @amino19 that's great to hear, thank you, but I think workflow is still not working could you please take a look

@warunicorn19: I think, it's failing, here's the [thread](https://layer5io.slack.com/archives/C011VPREG2Z/p1632338042094200?thread_ts=1632226264.088000&cid=C011VPREG2Z). :confused: 

@DelusionalOptimist: I dunno, what's wrong with label-commenter-config workflow! Any insights?

**Pull request merged**
