### PR TITLE
changed background color

### LINKED ISSUE #110: [Site] Background color change
**Current State of the GetNighthawk.dev site**
Currently, the hero section of the website as well as the "what is getnighthawk?" section has a grey background color.
check it out at - https://getnighthawk.dev/
chrome_Yd4XuBEZPf

**Desired State of the GetNighthawk.dev site**
The Figma design is a bit different for the hero section as it has a blue tone background color #C9FCF6. The "what is getnighthawk?" section is supposed to have a white background like all the other sections, instead of grey.
chrome_DrufrQo7Ga

Figma design link - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5884%3A12909

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by NikhilSharma03**
**Description**
Background color was different than desired color
Changed background color of header and main div

This PR fixes #110

### CODE REVIEW

**Comment by leecalcote** [comment]
@NikhilSharma03 thanks! Will you execute the commands outlined here?https://github.com/layer5io/getnighthawk/pull/113/checks?check_run_id=2611966386

More info on commit signing here - https://github.com/layer5io/getnighthawk/pull/113#issuecomment-843271099

**Comment by chinmaym07** [comment]
I tried to test these changes made by you locally . & it looks like this .. Can you please confirm .!
@NikhilSharma03 does it looks like this ? Then some more changes are required here ..

Screenshot_2021-05-18 GetNighthawk

**Comment by NikhilSharma03** [comment]
@chinmaym07 Thank you for informing me. I worked on that and these are the results for me. Can you please check??
Screenshot from 2021-05-18 22-55-44

**Comment by chinmaym07** [comment]
@vinayaksh42 when you scroll down the navbar also slides . Background Color on Navbar is still grey..Do we need to change this to `#C9FCF6` on scrolling ?

a


It looks better @NikhilSharma03 .. 
One more thing will please Sign off your commits .
Please run these commands mentioned here .
https://github.com/layer5io/getnighthawk/pull/113/checks?check_run_id=2611966386
I think both of your commits are not signed so you might need to run 
`git rebase --signoff HEAD~2` 
then run
`git push --force-with-lease origin changed_background_color`

**Review by vinayaksh42 — COMMENTED** [review]
All the changes are looking good. Try to follow this https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin for fixing the DCO issue

**Comment by NikhilSharma03** [comment]
@chinmaym07 I have updated the description and executed these two commands in my directory.

git rebase --signoff HEAD~2
git push --force-with-lease origin changed_background_color

Can you please check if anything's wrong??

**Comment by chinmaym07** [comment]
@NikhilSharma03 I think so all of your commits are signed now .. as `DCO` check is passing now ..
It can be merged . Thankyou for your contribution 👍🏻 🚀 💯

**Comment by vinayaksh42** [comment]
Great work @NikhilSharma03

**Review by vinayaksh42 — APPROVED** [review]

**Comment by vinayaksh42** [comment]
@NikhilSharma03 congrats on making your first contribution in Layer5!

**Comment by NikhilSharma03** [comment]
Thank you so much for the guidance and help @chinmaym07 and @vinayaksh42

**Comment by leecalcote** [comment]
Whoo-hoo!

**Pull request merged**
