### PR TITLE
[Docs] Remove GetNighthawk Reference

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**
This PR removes references to GetNighthawk.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Thank you, @theBeginner86 👌

**Comment by leecalcote** [comment]
I should have been more detailed and asked for the removal of that section entirely. Do you might making another update to delete the section?

**Comment by theBeginner86** [comment]
> I should have been more detailed and asked for the removal of that section entirely. Do you might making another update to delete the section?

Done!!
Initially, I was thinking that you meant to remove the section but then I realized that the [section](https://getnighthawk.dev/docs) was there on the nighthawk website as well so I thought I just need to change the name. 
But nonetheless, I removed it. 😅

**Comment by theBeginner86** [comment]
@leecalcote is it good now?
You meant to delete `Why GetNighthawk?`section, right?

**Comment by leecalcote** [comment]
Yes, this looks good.

**Pull request merged**
