### PR TITLE
[output] ability to natively convert nighthawk output to fortio output

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**
This PR:
* Removes the dependency on `nighthawk_output_transform`
* Makes transformation go native.
* Makes transformation more efficient and aligned with nighthawk's capability.
* Removes hacks.

**Why do we need this?**
Unlike `nighthawk_client` (CLI) `nighthawk_service` (gRPC service) doesn't offer output transformation to other formats. See https://github.com/envoyproxy/nighthawk/pull/152
The histogram that is constructed for performance tests is (at least for now) based on fortio's json output so we need the ability to transform.
The code here uses the same logic and the output structure that is implemented by the `nighthawk_output_transformer`

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Lgtm

**Comment by oschaaf** [comment]
Naive question probably .. but I wonder: why not wrap the nighthawk_transform binary to piggy back on this functionality being maintained at 0 cost?

**Comment by DelusionalOptimist** [comment]
Yes @oschaaf, that is a much feasible solution. In fact, this is what we're doing right now. The results are transformed using the binary shipped in Meshery server's image. However, both the Nighthawk binaries are pretty big in size (600 MB) and also need shared libraries. As we're trying to reduce meshery server's image size (1.7 GB rn) and also move to a lightweight base image, we probably need to get these out. The nighthawk_service would be soon running in a different container and this PR is an attempt to help out with transformation.
Another reason is to avoid running shell commands directly. But I don't know if this on its own is a big enough reason.

**Comment by warunicorn19** [comment]
@DelusionalOptimist is this PR good to merge?

**Comment by DelusionalOptimist** [comment]
@oschaaf since you're here and I'm not much sure if any thoughts have been put on this in the past, do you know why the nighthawk binaries published here are much bigger than the ones that are shipped in nighthawk-dev image? There seems to be a significant difference.

**Comment by oschaaf** [comment]
> @oschaaf since you're here and I'm not much sure if any thoughts have been put on this in the past, do you know why the nighthawk binaries published here are much bigger than the ones that are shipped in nighthawk-dev image? There seems to be a significant difference.

It is a bit of a guess, but over at envoyproxy/nighthawk there's  https://github.com/envoyproxy/nighthawk/blob/main/.bazelrc and https://github.com/envoyproxy/nighthawk/blob/main/.bazelversion.
Is there an equivalent of those being used for building the binaries that get published here?

**Pull request merged**
