### PR TITLE
nighthawk-meshery image crop fixed

### LINKED ISSUE #190: nighthawk-meshery image is cropped
**Description**

In the about and home section of https://getnighthawk.dev/ the image for nighthawk-meshery (https://getnighthawk.dev/assets/images/nighthawk-meshery.png) is cropped off, It should have been replaced.

**Expected Behavior**

https://getnighthawk.dev/assets/images/smp-standard.png This image has to placed there.

**Environment:**

- OS: Ubuntu
- Browser: Mozilla Firefox
- Version: 92.0
- Device: Laptop

---

**To Reproduce**

1. Go to https://getnighthawk.dev/about
2. Scroll down to end
3. See image at left

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Manish-210**
Signed-off-by: Manish Prajapati <210manishprajapati@gmail.com>

**Description**

This PR fixes #190

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@Manish-210 The aspect ratio is completely off, could you please fix that. 

Screenshot 2021-10-04 at 11 49 59 AM

**Comment by Manish-210** [comment]
Yeah, I have changed the aspect ratio. The sentence is going to a new line, will it be fine?

**Comment by warunicorn19** [comment]
@Manish-210 there's a merge conflict would you please take a look at that, also let's get the image a smidge bigger.

**Comment by Manish-210** [comment]
Yup, I have increased the image size to 10%.

**Review by warunicorn19 — APPROVED** [review]
Thank you @Manish-210

**Pull request merged**
