### PR TITLE
Fix: Navbar not responsive

### LINKED ISSUE #189: Navbar not responsive in any device view
**Description**

The website's navbar is not responsive and doesn't have a good UX, making the navbar less user responsive

**Expected Behavior**

- Hover Effects
- Well-aligned text
- Having it responsive on all device view

**Screenshots**

image
image
image

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by toth2000**
Signed-off-by: toth2000 <tothagata.bhattacharjee@gmail.com>

**Description**
This PR makes the navbar responsive on all devices.

image

image

This PR fixes #189 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@toth2000 let's discuss both your PRs on the websites' call tomorrow

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@toth2000 could you make it so that the logo and the burger menu are adjacent to each other in mobile view.

**Comment by toth2000** [comment]
@warunicorn19  For the logo and menu to be adjacent, the nav-list and menu icon need to be on a different div (otherwise current navbar issue persists). But if I try to put either the menu icon or nav-list on a different div the CSS styles don't get applied. I am not sure how to solve this, any help would be much appreciated.
image

**Comment by l5io** [comment]
Almost... there...

**Comment by leecalcote** [comment]
@toth2000 any success to report?

**Comment by toth2000** [comment]
Sorry, I have been busy the past few weeks with my semester exams and offline classes. I tried to implement the suggested changes but still, it is not working. I think it will be better to assign this issue to someone who is really good with CSS.

**Comment by leecalcote** [comment]
@toth2000, no problem at all. I completely understand.

**Comment by Abhijay007** [comment]
@leecalcote can I give it a try?

**Pull request closed without merging**
