### PR TITLE
joined Stewarded by and Organized by section together

### LINKED ISSUE #111: [Site] Stewarded by and Organized by section
**Current State of the GetNighthawk.dev site**
Currently, there are two different independent sections for Stewarded by and Organized by.
chrome_YJ3m6LxVeQ

**Desired State of the GetNighthawk.dev site**
The Figma design has both of these sections combined into one single section.
chrome_0yvlclrxEi

Figma design link - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5046%3A0

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
combined the Stewarded by and Organized by into one single section.
This PR fixes #111 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by JubayerJoy** [comment]
@leecalcote, I can't see the deployed result from netlify, please check if it's working for you.
Thanks! 
Screenshot (124)

**Comment by leecalcote** [comment]
@JubayerJoy you're right. The Netlify configuration for this site is incomplete. I'll send you an invite to the team account...

**Comment by JubayerJoy** [comment]
@leecalcote thank you for inviting, will look into it 👍

@Anita-ihuman awesome work! 
Even the most flawless work might have some improvement to be made, for you, I can see two,
1. There is some extra space at the bottom of the section, I found that it's caused by the `margin: 1rem auto`.

Screenshot (200)

2. There is a responsive issue with the text of this section.

Screenshot (201)

Good luck!

**Comment by vinayaksh42** [comment]
Great work @Anita-ihuman, I agree with the improvement suggestions made by @JubayerJoy

**Comment by JubayerJoy** [comment]
@vinayaksh42  & @leecalcote the design seems flawless and @Anita-ihuman has done a great job implementing it.

we should consider that this section gets the same background color as the navbar(scrolled) `i.e. #F8FAFF` cause it looks comparatively nicer. Here is the comparison:
1. Existing design:
Screenshot (203)

2. Suggestion
Screenshot (204)

  
 If we are looking to give this section a lot of focus then I suggest keeping it as the original.
Thanks!

**Review by JubayerJoy — APPROVED** [review]
@Anita-ihuman awesome work!
LGTM 👍

**Review by vinayaksh42 — APPROVED** [review]
Great work @Anita-ihuman

**Pull request merged**
