### PR TITLE
Added a no-script in the site giving jungle green having a catchy loo…

### LINKED ISSUE #186: Add Disabled Javascript in Getnighthawk
**Description**

Currently there's no notice for getnighthawk if javascript is disabled. When it is disabled it creating issues for website to run properly

**Expected Behavior**

A proper warning or notification type must appear at top showing that javascript is disabled

**Screenshots**

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
…k with yellow text w/signoff

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

**Description**

This PR fixes #186 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks @AnshumanDhiman

**Comment by AnshumanDhiman** [comment]
still showing project not participating to this PR only any idea ?

**Comment by warunicorn19** [comment]
@AnshumanDhiman i have no idea why, my PR this morning from this org. itself got approved. @navendu-pottekkat any idea why it's happening, is it because this repo doesn't have a `hacktoberfest` label?

**Comment by AnshumanDhiman** [comment]
image_2021-10-01_231959

**Comment by navendu-pottekkat** [comment]
Yes it is. I will fix that.

**Comment by navendu-pottekkat** [comment]
@warunicorn19 You would not need to label PRs if the repo has the `hacktoberfest` label. It would be automatically counted.

**Comment by warunicorn19** [comment]
oh okay.

**Pull request merged**
