### PR TITLE
[Site] Added hover effects on home page buttons

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
In the current state, the home page buttons on hover do not give any response ( which is not a good pattern for good UI experience ) 

## Before

https://user-images.githubusercontent.com/58226527/120101645-9f64b600-c164-11eb-89d6-2d8091c4c65e.mp4

## After Changes
- added hover effects on buttons

https://user-images.githubusercontent.com/58226527/120101647-ac81a500-c164-11eb-9be6-d13610672511.mp4

** Other area's where the effect is applied **
Screenshot from 2021-05-30 16-17-45

Screenshot from 2021-05-30 16-27-22

Screenshot from 2021-05-30 16-17-41

**Notes for Reviewers**
Let me know if there are any other changes we can make. Thank you.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by vinayaksh42 — COMMENTED** [review]
Nice work @NikhilSharma03

Suggestions required on this addition. @leecalcote @austinogiza

**Comment by leecalcote** [comment]
Looking good to me. If further effort is given here, it would ideal if the behavior mimicked that of the layer5.io site.


https://user-images.githubusercontent.com/7570704/120111288-f9e71d80-c136-11eb-8f2d-9618eb8aa5f9.mov

**Comment by NikhilSharma03** [comment]
Thank you for the suggestion @leecalcote . Can you please check?

## After Changes

https://user-images.githubusercontent.com/58226527/120190657-875d6700-c236-11eb-8c11-eb36cce37818.mp4

**Review by JubayerJoy — COMMENTED** [review]
LGTM 🚀

**Comment by vinayaksh42** [comment]
> ✔️ Website preview ready!
> 
> 🔨 Explore the source changes: [5b57e6d](https://github.com/layer5io/getnighthawk/commit/5b57e6d67d21556c88ebc85b129884ce7ea0727c)
> 
> 🔍 Inspect the deploy log: [https://app.netlify.com/sites/getnighthawk/deploys/60b4d0b20fa200000768c2dc](https://app.netlify.com/sites/getnighthawk/deploys/60b4d0b20fa200000768c2dc?utm_source=github&utm_campaign=bot_dl)
> 
> 😎 Browse the preview: [https://deploy-preview-122--getnighthawk.netlify.app](https://deploy-preview-122--getnighthawk.netlify.app?utm_source=github&utm_campaign=bot_dp)

Nice to see this working

**Comment by vinayaksh42** [comment]
Hey, @NikhilSharma03 There is a small conflict that you will have to resolve in order to get this PR merged

**Comment by NikhilSharma03** [comment]
@vinayaksh42 Can you please check. I was resolving conflict with the Github interface and these changes occured.

**Comment by NikhilSharma03** [comment]
@vinayaksh42 Can you please check. I resolved the conflict with the Github interface and these changes occurred.
Also the DCO check is not passing.

I think the files which are changes in the recent merge have been updated in the PR.

**Comment by JubayerJoy** [comment]
Hi @NikhilSharma03,
There seems to be a DCO issue, please follow the [instructions ](https://github.com/layer5io/getnighthawk/pull/122/checks?check_run_id=2719671742) to resolve them so it can be marged.
Thanks!

**Comment by NikhilSharma03** [comment]
@JubayerJoy I executed these commands but still, it's not verifying. Can you please check:

git commit --amend --no-edit --signoff

git push --force-with-lease origin hover_effect

**Comment by JubayerJoy** [comment]
@NikhilSharma03 you can try running these commands. it should resolve the issue of DCO.
```
git rebase --signoff HEAD~7
git push --force-with-lease origin hover_effect
```

**Comment by NikhilSharma03** [comment]
Screenshot from 2021-06-01 21-19-31

It's actually not pushing the changes??

**Comment by JubayerJoy** [comment]
I am not sure what's going wrong here, maybe try this instead:
```
git rebase -i 673a7f42b45192d5cff458667b6bf410df48aae0
git commit --amend --signoff
git push --force-with-lease origin hover_effect
```

**Comment by NikhilSharma03** [comment]
No, it's still not working. Should I make a new PR? 
Can you please help @vinayaksh42

**Comment by vinayaksh42** [comment]
> No, it's still not working. Should I make a new PR?
> Can you please help @vinayaksh42

@NikhilSharma03 , we recently had the DCO issue in this PR - https://github.com/layer5io/getnighthawk/pull/107
You can checkout the method that was used for fixing it, If nothing works we can take the last option of opening up a new PR

**Comment by NikhilSharma03** [comment]
@vinayaksh42 I guess i have a to make a new PR.You can close this one. Thank you.

**Pull request closed without merging**
