### PR TITLE
chore:Added responsive Navbar

### LINKED ISSUE #189: Navbar not responsive in any device view
**Description**

The website's navbar is not responsive and doesn't have a good UX, making the navbar less user responsive

**Expected Behavior**

- Hover Effects
- Well-aligned text
- Having it responsive on all device view

**Screenshots**

image
image
image

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by anirudh-bukka**
Signed-off-by: anirudh-bukka <anirudh.bukka@gmail.com>

**Description**

This PR fixes #189 

**Notes for Reviewers**
Added hover effects and corrected the position of the drop down menu list from the hamburger button.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
@anirudh-bukka great work, it looks good for mobile view, just do the same changes for tab view as well ( max-width: 768px) and in that screen size try to shift nav icon bit towards right 

image

you can also take reference from this article if you want to read more about media queries: https://www.geeksforgeeks.org/how-to-target-desktop-tablet-and-mobile-using-media-query/

**Comment by anirudh-bukka** [comment]
> @anirudh-bukka great work, it looks good for mobile view, just do the same changes for tab view as well ( max-width: 768px) and in that screen size try to shift nav icon bit towards right
> 
> image
> 
> you can also take reference from this article if you want to read more about media queries: https://www.geeksforgeeks.org/how-to-target-desktop-tablet-and-mobile-using-media-query/

On it

**Review by Abhijay007 — APPROVED** [review]
LGTM 👍 , great work @anirudh-bukka

**Review by YashKamboj — COMMENTED** [review]
@anirudh-bukka Good Work!!! just one small thing , i the "menu" written after the icon is removed ,so if you bring that back would be great .

**Comment by anirudh-bukka** [comment]
> @anirudh-bukka Good Work!!! just one small thing , i the "menu" written after the icon is removed ,so if you bring that back would be great .

Thanks @YashKamboj , okay I will try to add it in tablet viewport size - as it would be cluttered and congested in mobile phones viewport size.

**Comment by anirudh-bukka** [comment]
> LGTM 👍 , great work @anirudh-bukka

Thanks @Abhijay007 !

**Comment by YashKamboj** [comment]
@anirudh-bukka why don't you try and send the screenshot

**Comment by YashKamboj** [comment]
> > @anirudh-bukka Good Work!!! just one small thing , i the "menu" written after the icon is removed ,so if you bring that back would be great .
> 
> Thanks @YashKamboj , When I started working on this issue, the word 'menu' was not present in the forked and cloned files, so I thought the "menu" was not supposed to be there.
> 
> But I felt, having the word 'menu' would make the navbar cluttered and congested. What do you say?

I guess it will look great even without menu written

**Review by YashKamboj — APPROVED** [review]

**Comment by warunicorn19** [comment]
Might be better toh have just the nighthawk logo in smaller views than the text logo. What do you think @debo19

**Comment by adithyaakrishna** [comment]
@anirudh-bukka @YashKamboj @warunicorn19 The UI/UX Convention is not to have a title saying `menu` as the icon itself stands for hamburger menu so what do you guys think if it can be removed for mobile devices?

**Comment by warunicorn19** [comment]
@adithyaakrishna the title `menu` has already been removed.

**Comment by adithyaakrishna** [comment]
My bad xD, I didnt see that :(

**Comment by debo19** [comment]
> Might be better toh have just the nighthawk logo in smaller views than the text logo. What do you think @debo19

@warunicorn19 It might look too empty though.🤔  I think this looks fine.

**Review by Abhijay007 — APPROVED** [review]
LGTM 👍

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @anirudh-bukka

**Comment by anirudh-bukka** [comment]
> LGTM 👍

Thanks @Abhijay007 for helping me in all the set-up and pushing my first pr!

**Pull request merged**
