### PR TITLE
fixed slack star workflow

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
Tried fixing the workflow to count the stars on getnighthawk on slack
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — APPROVED** [review]
LGTM 🎉. Thanks @warunicorn19 !

**Comment by DelusionalOptimist** [comment]
@warunicorn19 looks good. While you're at it, why not fix https://github.com/warunicorn19/getnighthawk/blob/b795c37443caa4dfa53e6d9dcae383de8c703efc/.github/workflows/slack.yml#L16 as well :slightly_smiling_face: . It should be `getnighthawk` and not `nighthawk-go`

**Comment by warunicorn19** [comment]
> @warunicorn19 looks good. While you're at it, why not fix https://github.com/warunicorn19/getnighthawk/blob/b795c37443caa4dfa53e6d9dcae383de8c703efc/.github/workflows/slack.yml#L16 as well 🙂 . It should be `getnighthawk` and not `nighthawk-go`

Made the change @DelusionalOptimist 😄

**Review by DelusionalOptimist — APPROVED** [review]
LGTM. :heavy_check_mark:
Thanks @warunicorn19 :+1:

**Pull request merged**
