### PR TITLE
Grumpyyash/my changes

### LINKED ISSUE #36: [Site] Hero Section (get started)
**Current Behavior**

The start section/hero section of getnighthawk is occupied by the previous following section:
chrome_xuuDsn5aMa

**Desired Behavior**

needs to be implemented according to the following [figma ](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236)mockup
Use a placeholder logo until the final getnighthawk logo is prepared.

chrome_jEx55cf2sK

---
**Resources**

Refer to the 9th page of this [doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w/edit#) to get more info about color scheme and Typography

### PR DESCRIPTION
**Pull request by Grumpyyash**
Added the hero-section on the homepage of the getnighthawk project.

This PR fixes #36 
hero

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
🎈 

@Grumpyyash will you execute these instructions - https://github.com/layer5io/getnighthawk/pull/37/checks?check_run_id=1848437578

**Comment by leecalcote** [comment]
Good, good

**Review by aneeshnema — COMMENTED** [review]
Looks good to me 💯

**Review by aneeshnema — APPROVED** [review]

**Review by cekbote — APPROVED** [review]

**Comment by cekbote** [comment]
LGTM

**Review by vinayaksh42 — APPROVED** [review]

**Comment by vinayaksh42** [comment]
Looks good, I think we should start removing the older sections as we go on with the implementation of newer UI.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay!

**Pull request merged**
