### PR TITLE
added docker build

### PR DESCRIPTION
**Pull request by kumarabd**
Signed-off-by: kumarabd <abishekkumar92@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Do we have an existing hub repo for this image?

**Comment by leecalcote** [comment]
New Docker Hub repo created - https://hub.docker.com/r/layer5/getnighthawk

**Comment by leecalcote** [comment]
IMAGE_NAME secret created with the docker hub org/repo name.

**Review by leecalcote — APPROVED** [review]

**Comment by kumarabd** [comment]
@leecalcote sorry had missed it, thanks for the help.

**Pull request merged**
