### PR TITLE
Issue-189 (Chore): Added responsive Navbar

### LINKED ISSUE #189: Navbar not responsive in any device view
**Description**

The website's navbar is not responsive and doesn't have a good UX, making the navbar less user responsive

**Expected Behavior**

- Hover Effects
- Well-aligned text
- Having it responsive on all device view

**Screenshots**

image
image
image

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

This PR is related to  #240, I shifted CSS to different folders in order to make changes live on the site 

This PR fixes #189 

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by YashKamboj — COMMENTED** [review]
No change in preview @Abhijay007

**Review by YashKamboj — APPROVED** [review]
LGTM!!!!👌👌

**Comment by sidd-oo** [comment]
This looks good to me @Abhijay007 Keep up the good work.

**Review by debo19 — APPROVED** [review]

**Comment by Abhijay007** [comment]
don't know why 😅 but it is still not working :(

**Comment by debo19** [comment]
@Abhijay007 it takes some time to deploy. Lets check in a while

**Comment by warunicorn19** [comment]
Currently I dont see the hamburger menu at all😅😅 image

Would you be able to look further into this @Abhijay007 or should we create a separate issue? Considering that your lfx mentorship is going on😃.

**Pull request merged**
