### PR TITLE
[Site] Fixed Docs Section 1/Overview Responsiveness

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**
- There were some responsive issues in the docs section 1/overview page

### Screenshot
Screenshot from 2021-08-11 16-44-21

Screenshot from 2021-08-11 16-44-26

Screenshot from 2021-08-11 16-44-32

## After Changes
Screenshot from 2021-08-11 16-44-38

Screenshot from 2021-08-11 16-44-49

Screenshot from 2021-08-11 16-44-55

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — APPROVED** [review]
LGTM!🎉, Thanks @NikhilSharma03

**Comment by vinayaksh42** [comment]
Great changes @NikhilSharma03 , This feels a lot more responsive

**Review by vinayaksh42 — APPROVED** [review]

**Comment by vinayaksh42** [comment]
opera_XCheW4WPA0
@NikhilSharma03 can you checkout the home page of docs. I think it would be great to have the same padding and margin for this page as well.

**Comment by leecalcote** [comment]
I missed @vinayaksh42's last comment and requested change. Please do address this.

**Comment by leecalcote** [comment]
I'm sorry about that, gents. I missed that last request for an update.￼￼

**Comment by NikhilSharma03** [comment]
> opera_XCheW4WPA0
> @NikhilSharma03 can you checkout the home page of docs. I think it would be great to have the same padding and margin for this page as well.

Yes i have fixed it in my last PR.

**Comment by NikhilSharma03** [comment]
> I'm sorry about that, gents. I missed that last request for an update.￼￼

Flash : I am the fastest man alive
@leecalcote : Hold my merge :rofl:

**Pull request merged**
