### PR TITLE
Chore: Formatted community Mailing list component

### LINKED ISSUE #229: Form for community mailing list
This one was really for me to create a Google Group mailing list, which I believe we have now (see the mailing list section on the main page). Yes, you're right - we essentially want the same thing that we have on amp-spec.io and meshery.io. We essentially have that now, but are missing two things:

1. a text field to receive visitor's email address, so that they can subscribe to the community mailer. Example - https://smp-spec.io#subscribe
2. a formatting issue on https://getnighthawk.dev/subscribe. Margin is needed to separate the nav bar and prevent overlap:
Screen Shot 2021-12-23 at 10 45 59 AM

_Originally posted by @leecalcote in https://github.com/layer5io/getnighthawk/issues/44#issuecomment-1000419189_

### PR DESCRIPTION
**Pull request by Abhijay007**
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

**Description**

Formatted community Mailing list component

This PR fixes #229 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by YashKamboj** [comment]
@Abhijay007 I think you should make the field mandatory and little bigger because it looks really empty.

**Comment by Abhijay007** [comment]
> @Abhijay007 I think you should make the field mandatory and little bigger because it looks really empty.

ok, so you are talking about validations, right?

**Comment by Abhijay007** [comment]
https://user-images.githubusercontent.com/64387054/148189667-94af6272-8065-47ac-b9ea-75176394fccb.mp4

**Comment by Abhijay007** [comment]
@leecalcote @YashKamboj please review :)

**Review by YashKamboj — APPROVED** [review]

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @Abhijay007

**Pull request merged**
