### PR TITLE
Updated README.md  (Images & Links)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
**Description**
Updated README.md  (Images & Links)

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Good!

I still need to get you that About Layer5 text.

**Comment by UtkarshMishra12** [comment]
@leecalcote What about this?
**[Layer5](https://layer5.io/)'s cloud native application and infrastructure management software enables organizations to expect more from their infrastructure. We embrace developer-defined infrastructure. We empower developers to change how they write applications, support operators in rethinking how they run modern infrastructure and enable product owners to regain full control over their product portfolio.**

**Comment by leecalcote** [comment]
Sounds good. If you'll exchange "developer" for "engineer" in the final sentence that will be more inclusive. Let's leave "developer-defined", though.

**Review by Chadha93 — APPROVED** [review]
Thank you @UtkarshMishra12

**Pull request merged**
