### PR TITLE
adding googleTagManager tracking code to all pages omesh-omg issue 291

### LINKED ISSUE #291: Add Google Tag Manager tracking code to all pages
**Current Behavior**

This issue is for enabling Google Analytics on https://getnighthawk.dev/ . The following code has to be added to all the pages of the website to enable tracking.
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TXGF3DB');</script>
<!-- End Google Tag Manager -->
```
**Desired Behavior**

---

**Resources**

**Alternatives / Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by omesh-omg**
Signed-off-by: omesh-omg <kumawatomesh4022@gmail.com>

**Description**
addes google tag manager to the top of header
This PR fixes #291 

**[Signed commits](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Savio629** [comment]
This code needs to be added to all pages of getnighthawk website

**Comment by omesh-omg** [comment]
> This code needs to be added to all pages of getnighthawk website

as per what I understood every page uses same file docs.html as a structure so on all the pages it will be visible I have checked in the console as well 

@Savio629 
about page
image
docs page
image
home page
image

**Comment by sandramsc** [comment]
CC: @abhijeetgauravm 

@omesh-omg Thanks for your contribution, just to inquire, it appears as though there is an existing Google Tag manager script already integrated in the pages referenced in the PR as well as the original issue. Was the goal to **update** the Google tag manager instead?

**Comment by omesh-omg** [comment]
@sandramsc I don't have much knowledge about but the issue was just to add it Google analytics script to the top of the file , I didn't find any other script added in the main branch regarding this

**Comment by omesh-omg** [comment]
I think this will be helpful

**Comment by abhijeetgauravm** [comment]
> CC: @abhijeetgauravm
> 
> @omesh-omg Thanks for your contribution, just to inquire, it appears as though there is an existing Google Tag manager script already integrated in the pages referenced in the PR as well as the original issue. Was the goal to **update** the Google tag manager instead? tag

Yeah the Google Tag manager script already integrated in the pages, as i can see to the pages of the [site](https://getnighthawk.dev/). // @ayushthe1 @vishalvivekm @Savio629 Thoughts?

**Comment by sandramsc** [comment]
> > CC: @abhijeetgauravm
> > @omesh-omg Thanks for your contribution, just to inquire, it appears as though there is an existing Google Tag manager script already integrated in the pages referenced in the PR as well as the original issue. Was the goal to **update** the Google tag manager instead? tag
> 
> Yeah the Google Tag manager script already integrated in the pages, as i can see to the pages of the [site](https://getnighthawk.dev/). // @ayushthe1 @vishalvivekm @Savio629 Thoughts?

If the Google tag manager already exists and the initial issue was to add one then the issue wasn't _triaged_ effectively as essentially this wasn't an issue in the first place...

**Comment by iArchitSharma** [comment]
@omesh-omg @sandramsc @abhijeetgauravm 
Tag manager has to be added in config file
FYI Google Tag Manager ID and Google Analytics Tracking ID are two different components, we have Analytics ID
image

**Comment by iArchitSharma** [comment]
> @omesh-omg @sandramsc @abhijeetgauravm FYI Google Tag Manager ID and Google Analytics Tracking ID are two different components, what we already have is **Analytics ID** and that is what was asked in the issue image

Closing the PR!

**Pull request closed without merging**
