### PR TITLE
Updated build to Go 1.19

### PR DESCRIPTION
**Pull request by MRafaydev**
Signed-off-by: Muhammad Rafay <muhammadrafay7655@gmail.com>

**Description**
This change updates the getnighthawk codebase to use Go 1.19 instead of Go 1.14 as the build environment. The reason for this change is that Go 1.14 is considered deprecated and is no longer receiving patches, making it less stable and compatible than more recent versions of the Go language.

This PR fixes #
This pull request updates the getnighthawk  codebase to build with Go 1.19 instead of Go 1.18. Go 1.18 is should be considered as deprecated and no longer receives patches, so updating to a newer and maintained version will ensure stability and compatibility for getnighthawk.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @MRafaydev! This PR was somehow overlooked.

@ShivangShandilya will you assist in reviewing this?

**Comment by ShivangShandilya** [comment]
> Thank you, @MRafaydev! This PR was somehow overlooked.
> 
> @ShivangShandilya will you assist in reviewing this?

Sure I'll take any learning opportunity I can. Thanks 😁

**Comment by ShivangShandilya** [comment]
From what I can see, it's a simple update in the Go version and the addition of some indirect dependencies. The syntax and formatting of `go.mod` file seem correct based on Go modules documentation.

Yup, looks good to me

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Pull request merged**
