### PR TITLE
small issue in the vertical navbar  #350 omesh-omg

### LINKED ISSUE #350: [Bug] small issue in the vertical navbar link css
#### Current Behavior
in the vertical navbar the 4th doc link [RECENT DISCUSSIONS ON NIGHTHAWK] goes out of the navbar 
image

#### Expected Behavior
image

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor Resources

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=5046-0&mode=design&t=UYVaGhic2LY8EXee-0)
- Meshery UI Nighthawk (Performance) in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=2-5814&mode=design&t=Gt14dmRRlpL09apZ-0)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by omesh-omg**
**Description**
changes in the css to keep the text within the nav-bar
This PR fixes #350 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Hey @omesh-omg Please sign-off your commit to pass DCO check.

**Comment by omesh-omg** [comment]
Okay

**Review by abhijeetgauravm — COMMENTED** [review]
@omesh-omg the changes looks good. Please sign-off your commits to pass DCO! 
image
One suggestion from my side would be, can we adjust hamburger menu towards left end(screen width ~412 -768 px), as u can see it's not looking appealing!

**Comment by omesh-omg** [comment]
image
I have already signed off commit here in the  last commit @abhijeetgauravm if u can access it please try or I will submit another pull request

**Comment by omesh-omg** [comment]
@abhijeetgauravm  also the hamburger menu problem is in another issue it is only visible in the native build or the one we run on our system on the live version we can't see the hamburger menu It is some technical fault it is already solved by someone and merged but it doesn't show up in the deployed website as I read in the pull request discussion
here are the links:
https://github.com/layer5io/getnighthawk/issues/258
you can check it out here you will get to know clearly

**Comment by iArchitSharma** [comment]
Closing this PR as duplicate exist https://github.com/layer5io/getnighthawk/pull/356

**Pull request closed without merging**
