### PR TITLE
created the new footer

### PR DESCRIPTION
**Pull request by Grumpyyash**
Signed-off-by: Yash Vardhan <yashvardhan513@gmail.com>

Created the new-footer as per the Figma designs for getnighthawk-homepage.

footer

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Oh, no. We have some miscommunication here. The expanded site footer that we currently have is an improvement on the design. Either the current footer or one like that of smp-spec.io will work.

**Comment by Grumpyyash** [comment]
okay, let's just keep it as it is then. I will close this PR

**Comment by leecalcote** [comment]
Oh, @Grumpyyash. Now that I look at the footer again, there is something to be done:

The copyright doesn't need to be prominent. It can be moved beneath the footer links.

**Comment by Grumpyyash** [comment]
@leecalcote are you talking about this PR's footer or the original one that we have? If it is about the original one, I can take that issue and fix it up and if it's about this one, it doesn't matter because I will close down this PR and keep the original footer only.

**Comment by vinayaksh42** [comment]
@Grumpyyash as talked over slack we are not implementing this particular design from the Figma mockup.  We are instead going with the footer that we currently have already.

The footer that we have currently requires a couple of fixes. The `2021 © Layer5, Inc.` Needs to be moved one level down, similar to this image:
chrome_cWHcCub6H1

You can make a new PR consisting of all these changes.

**Comment by Grumpyyash** [comment]
okay, I'll do it

**Pull request closed without merging**
