### PR TITLE
fixed footer on web

### LINKED ISSUE #108: [Site] Live site needs to match with the design
**Current State of the GetNighthawk.dev site**
A brief description of what the problem is.

The background colors, alignment, and spacing doesn't match the design

eg.
Screenshot 2021-05-14 at 5 46 58 AM

**Desired State of the GetNighthawk.dev site**
A brief description of the change you are requesting.

Matching all the alignments, colors, and spacing with the design https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5884%3A12909

eg.
Screenshot 2021-05-14 at 5 22 28 AM

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

### PR DESCRIPTION
**Pull request by akashc777**
**Description**

This PR fixes #108 

**Notes for Reviewers**
hero-section-div was not closed which forced other elements to align center. 

few suggestions:
Please avoid using  !important in css/scss since forcing the style is not a good practice 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Grumpyyash — APPROVED** [review]
LGTM! Good work @akashc777!

**Review by vinayaksh42 — CHANGES_REQUESTED** [review]
On changing screen size to bigger screen size the "copyright text" and "social media" icons move towards left side 
chrome_OLR9nmFtpn

**Comment by vinayaksh42** [comment]
Hey, @akashc777 any update on this Pull Request?

**Comment by akashc777** [comment]
Hi @vinayaksh42 I'm currently held some other work ... I won't be active for the next 2 months ... feel free to assign this issue to some else

**Comment by vinayaksh42** [comment]
Closing this PR as a new PR https://github.com/layer5io/getnighthawk/pull/129 has been made for the same issue

**Pull request closed without merging**
