### PR TITLE
[Site] Hover Effect on Buttons --signoff

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
Added Hover Effect on buttons

## After Changes

https://user-images.githubusercontent.com/58226527/120430347-82162e80-c394-11eb-8acf-7be82ba9a34e.mp4

This PR fixes #122 

**Notes for Reviewers**
The previous PR, was showing an error even it was committed with --signoff. So I created a new PR as @vinayaksh42 suggested.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@JubayerJoy and @vinayaksh42 Can you please review. Thank you.

**Review by leecalcote — APPROVED** [review]
Looking good, @NikhilSharma03 👍

**Review by JubayerJoy — APPROVED** [review]
LGTM 🚀

**Review by vinayaksh42 — APPROVED** [review]
nice work @NikhilSharma03

**Comment by NikhilSharma03** [comment]
Thank you @leecalcote @JubayerJoy @vinayaksh42 😊 .

**Pull request merged**
